apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  params:
    - name: IMAGE
      type: string
  workspaces:
    - name: shared-workspace

  tasks:
    - name: npminstall
      taskRef:
        name: npminstall
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: tests
      runAfter:
        - npminstall
      taskRef:
        name: jasmine-tests
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: build
      runAfter:
        - tests
      taskRef:
        name: build-image
      params:
        - name: IMAGE
          value: $(params.IMAGE)
      workspaces:
        - name: source
          workspace: shared-workspace
