apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npminstall
spec:
  workspaces:
    - name: source
  steps:
    - name: install
      image: node:18
      workingDir: $(workspaces.source.path)
      script: |
        npm install
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jasmine-tests
spec:
  workspaces:
    - name: source
  steps:
    - name: test
      image: node:18
      workingDir: $(workspaces.source.path)
      script: |
        npm install
        npm test
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-image
spec:
  params:
    - name: IMAGE
      type: string
  workspaces:
    - name: source
  steps:
    - name: build
      image: gcr.io/kaniko-project/executor:latest
      workingDir: $(workspaces.source.path)
      args:
        - "--dockerfile=Dockerfile"
        - "--destination=$(params.IMAGE)"
        - "--context=$(workspaces.source.path)"
